ignore:
  - "src/WebSocket.js"
  - "src/index.js"
  - "src/actions/WebSocket.js"
  - "src/middlewares/WebSocketMiddleware.js"
  - "src/reducers/index.js"
  - "src/views/Split.js"
  - "src/views/Labelling.js"
  - "src/views/**/*.js"
  - "src/components/upload/ServerUpload.jsx"
  - "src/components/upload/UploadDouble.jsx"
  - "src/components/advanced/Checkbox.js"
  - "src/components/advanced/Incremental.js"
  - "src/components/advanced/IncrementalTable.js"