ignore:
  - "src/WebSocket.js"
  - "src/index.js"
  - "src/actions/WebSocket.js"
  - "src/middlewares/WebSocketMiddleware.js"
  - "src/reducers/index.js"
  - "src/views/**/*.js"
  - "src/views/Split.js"
  - "src/views/Labelling.js"
